import React, { useEffect, useState } from 'react';
import { BadgeCheck, BriefcaseBusiness, Building2, Check, Clock3, RefreshCw, ShieldCheck, Truck, X } from 'lucide-react';
import { fetchEcosystemReviewQueue, reviewKuwaitiJob, reviewSupplier } from '../../lib/ecosystemClient';
import { KuwaitiJobPost, SupplierProfile } from '../../types/majal';

export const EcosystemApprovals: React.FC = () => {
  const [suppliers,setSuppliers]=useState<SupplierProfile[]>([]), [jobs,setJobs]=useState<KuwaitiJobPost[]>([]);
  const [loading,setLoading]=useState(true), [error,setError]=useState(''), [busy,setBusy]=useState('');
  const load=()=>{setLoading(true);fetchEcosystemReviewQueue().then(r=>{setSuppliers(r.suppliers);setJobs(r.jobs);setError('');}).catch(e=>setError(e instanceof Error?e.message:'تعذّر تحميل طابور الاعتمادات.')).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const supplierDecision=async(id:string,decision:'VERIFIED'|'NEEDS_ACTION')=>{setBusy(id);try{await reviewSupplier(id,decision,decision==='NEEDS_ACTION'?'يرجى استكمال بيانات السجل أو مستندات المورد.':'');await load();}catch(e){setError(e instanceof Error?e.message:'تعذّر اعتماد المورد.');}finally{setBusy('')}};
  const jobDecision=async(id:string,decision:'APPROVED'|'REJECTED')=>{setBusy(id);try{await reviewKuwaitiJob(id,decision,decision==='REJECTED'?'الإعلان يحتاج تعديلًا قبل النشر.':'');await load();}catch(e){setError(e instanceof Error?e.message:'تعذّر مراجعة الإعلان.');}finally{setBusy('')}};
  return <div className="space-y-6">
    <section className="glass-panel rounded-3xl p-5 border border-white/10 flex flex-col md:flex-row md:items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="w-11 h-11 rounded-2xl bg-gold-500/10 border border-gold-300/20 grid place-items-center"><ShieldCheck className="w-5 h-5 text-gold-300"/></span><div><h2 className="font-black text-lg">بوابة الاعتمادات</h2><p className="text-xs text-slate-400 mt-1">طابور واحد للموردين والوظائف الكويتية بدل إضافة شاشات مبعثرة.</p></div></div><button onClick={load} className="px-4 py-2.5 rounded-xl bg-white/5 border border-white/10 text-xs font-black flex items-center gap-2"><RefreshCw className="w-4 h-4"/>تحديث</button></section>
    {error&&<div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-400/20 text-xs text-rose-200">{error}</div>}
    {loading?<div className="text-center py-10 text-sm text-slate-500">جارٍ تحميل الطابور…</div>:<div className="grid xl:grid-cols-2 gap-6">
      <section className="space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Truck className="w-5 h-5 text-emerald-300"/><h3 className="font-black">اعتماد الموردين</h3></div><span className="text-[10px] text-slate-500">{suppliers.length} بانتظار القرار</span></div>{suppliers.length?suppliers.map(s=><article key={s.id} className="glass-card rounded-2xl p-5 border border-white/10 space-y-3"><div className="flex justify-between gap-3"><div><div className="text-[10px] text-emerald-300 font-black">{s.category}</div><h4 className="font-black mt-1">{s.commercialName}</h4></div><span className="text-[10px] px-2 py-1 rounded-full bg-amber-500/10 text-amber-300 h-fit">{s.verificationStatus==='PENDING'?'طلب تحقق':'غير معتمد'}</span></div><div className="text-xs text-slate-400 leading-6">السجل: <span dir="ltr" className="text-slate-200">{s.commercialRegistrationNo||'غير مدخل'}</span><br/>{s.description||'لا توجد نبذة إضافية.'}</div><div className="flex gap-2"><button disabled={busy===s.id||!s.commercialRegistrationNo} onClick={()=>supplierDecision(s.id,'VERIFIED')} className="flex-1 py-2.5 rounded-xl bg-emerald-400 text-slate-950 text-xs font-black disabled:opacity-40 flex items-center justify-center gap-1.5"><Check className="w-4 h-4"/>اعتماد</button><button disabled={busy===s.id} onClick={()=>supplierDecision(s.id,'NEEDS_ACTION')} className="px-4 py-2.5 rounded-xl bg-amber-500/10 border border-amber-400/20 text-amber-300 text-xs font-black">استكمال</button></div></article>):<div className="rounded-2xl p-6 border border-dashed border-white/10 text-center text-xs text-slate-500"><BadgeCheck className="w-6 h-6 mx-auto text-emerald-300 mb-2"/>لا توجد طلبات موردين معلقة.</div>}</section>
      <section className="space-y-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><BriefcaseBusiness className="w-5 h-5 text-sky-300"/><h3 className="font-black">وظائف كويتية</h3></div><span className="text-[10px] text-slate-500">{jobs.length} إعلان بانتظار المراجعة</span></div>{jobs.length?jobs.map(j=><article key={j.id} className="glass-card rounded-2xl p-5 border border-white/10 space-y-3"><div className="flex justify-between gap-3"><div><div className="text-[10px] text-sky-300 font-black flex items-center gap-1"><Building2 className="w-3 h-3"/>{j.employerName}</div><h4 className="font-black mt-1">{j.title}</h4></div><span className="text-[10px] px-2 py-1 rounded-full bg-amber-500/10 text-amber-300 h-fit flex items-center gap-1"><Clock3 className="w-3 h-3"/>معلّق</span></div><p className="text-xs text-slate-400 leading-6 line-clamp-4">{j.description}</p><div className="text-[10px] text-slate-500">{j.location} · {j.department||'عام'} · للكويتيين فقط</div><div className="flex gap-2"><button disabled={busy===j.id} onClick={()=>jobDecision(j.id,'APPROVED')} className="flex-1 py-2.5 rounded-xl bg-sky-400 text-slate-950 text-xs font-black disabled:opacity-40 flex items-center justify-center gap-1.5"><Check className="w-4 h-4"/>موافقة ونشر</button><button disabled={busy===j.id} onClick={()=>jobDecision(j.id,'REJECTED')} className="px-4 py-2.5 rounded-xl bg-rose-500/10 border border-rose-400/20 text-rose-300 text-xs font-black flex items-center gap-1"><X className="w-4 h-4"/>رفض</button></div></article>):<div className="rounded-2xl p-6 border border-dashed border-white/10 text-center text-xs text-slate-500"><BadgeCheck className="w-6 h-6 mx-auto text-sky-300 mb-2"/>لا توجد إعلانات معلقة.</div>}</section>
    </div>}
  </div>;
};
