import React, { FormEvent, useEffect, useState } from 'react';
import { BriefcaseBusiness, CheckCircle2, MapPin, ShieldCheck, UserCheck, X } from 'lucide-react';
import { applyToKuwaitiJob, fetchPublicEcosystem } from '../../lib/ecosystemClient';
import { KuwaitiJobPost } from '../../types/majal';
import { store } from '../../lib/store';
import { useDialogBehavior } from '../../hooks/useDialogBehavior';

const employmentLabel: Record<string,string> = { FULL_TIME:'دوام كامل', PART_TIME:'دوام جزئي', CONTRACT:'عقد', INTERNSHIP:'تدريب' };

export const KuwaitiJobs: React.FC = () => {
  const [jobs,setJobs]=useState<KuwaitiJobPost[]>([]), [loading,setLoading]=useState(true);
  const [selected,setSelected]=useState<KuwaitiJobPost|null>(null);
  const [summary,setSummary]=useState(''), [years,setYears]=useState('0'), [declare,setDeclare]=useState(false);
  const [busy,setBusy]=useState(false), [message,setMessage]=useState(''), [error,setError]=useState('');
  const close=()=>{setSelected(null);setMessage('');setError('');setDeclare(false)};
  const dialogRef=useDialogBehavior<HTMLDivElement>(Boolean(selected),close);
  useEffect(()=>{fetchPublicEcosystem().then(r=>setJobs(r.jobs)).catch(()=>setJobs([])).finally(()=>setLoading(false));},[]);
  const isAuthenticated=store.activeUser.id!=='anonymous';
  const submit=async(e:FormEvent)=>{e.preventDefault(); if(!selected)return; setBusy(true);setError('');try{const r=await applyToKuwaitiJob(selected.id,{summary,yearsExperience:Number(years),kuwaitiDeclaration:true});setMessage(`تم إرسال طلبك. ${r.note}`);}catch(err){setError(err instanceof Error?err.message:'تعذّر إرسال الطلب.');}finally{setBusy(false)}};
  if(!loading&&!jobs.length) return null;
  return <section className="glass-panel rounded-[28px] p-5 md:p-6 border border-white/10 space-y-5">
    <div className="flex items-start justify-between gap-4"><div className="flex gap-3"><span className="w-11 h-11 rounded-2xl bg-emerald-500/10 border border-emerald-400/20 grid place-items-center shrink-0"><BriefcaseBusiness className="w-5 h-5 text-emerald-300"/></span><div><div className="flex items-center gap-2 flex-wrap"><h2 className="text-lg font-black">فرص كويتية عبر مجال</h2><span className="px-2 py-1 rounded-full bg-white/5 border border-white/10 text-[9px] text-slate-400">بوابة مضبوطة وليست سوق إعلانات مفتوح</span></div><p className="text-xs text-slate-400 mt-1 leading-6">تظهر هنا فقط الوظائف التي وافقت عليها إدارة مجال. مخصصة لتوظيف الكويتيين لدى المنشآت والموردين في المنظومة.</p></div></div><span className="text-[10px] text-emerald-300 font-black whitespace-nowrap">{jobs.length} فرصة</span></div>
    {loading?<div className="text-xs text-slate-500 py-4">جارٍ تحميل الفرص…</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{jobs.slice(0,6).map(job=><article key={job.id} className="rounded-2xl p-4 bg-white/[0.03] border border-white/10"><div className="flex justify-between gap-3"><div><div className="text-[10px] text-emerald-300 font-black">{job.employerName}</div><h3 className="font-black mt-1">{job.title}</h3></div><ShieldCheck className="w-4 h-4 text-emerald-300 shrink-0"/></div><div className="mt-3 flex gap-2 flex-wrap text-[10px] text-slate-500"><span className="flex items-center gap-1"><MapPin className="w-3 h-3"/>{job.location}</span><span>{employmentLabel[job.employmentType]||job.employmentType}</span>{job.department&&<span>{job.department}</span>}</div><p className="text-xs text-slate-400 leading-6 mt-3 line-clamp-3">{job.description}</p><button onClick={()=>setSelected(job)} className="mt-4 w-full py-2.5 rounded-xl bg-emerald-500/10 border border-emerald-400/20 text-emerald-300 text-xs font-black">عرض والتقديم</button></article>)}</div>}
    <p className="text-[10px] text-slate-500 leading-5">اعتماد الإعلان من الإدارة لا يعني اعتماد المرشح أو التحقق من جنسيته. التحقق الرسمي من الهوية/الجنسية يحتاج تكاملًا حكوميًا معتمدًا.</p>
    {selected&&<div className="fixed inset-0 z-[85] bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4" onMouseDown={e=>e.target===e.currentTarget&&close()}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="job-detail-title" className="w-full max-w-xl glass-panel rounded-[28px] border border-white/10 p-6 relative"><button onClick={close} aria-label="إغلاق" className="absolute top-4 left-4 p-2 text-slate-400 hover:text-white"><X className="w-4 h-4"/></button><div className="pr-1"><div className="text-[10px] text-emerald-300 font-black">{selected.employerName}</div><h3 id="job-detail-title" className="text-xl font-black mt-1">{selected.title}</h3><p className="text-xs text-slate-400 mt-2">{selected.location} · {employmentLabel[selected.employmentType]}</p></div><p className="text-sm text-slate-300 leading-7 mt-5">{selected.description}</p>{selected.requirements.length>0&&<div className="mt-4"><div className="text-xs font-black mb-2">المتطلبات</div><div className="space-y-1">{selected.requirements.map((r,i)=><div key={i} className="text-xs text-slate-400">• {r}</div>)}</div></div>}{message?<div className="mt-6 p-4 rounded-2xl bg-emerald-500/10 border border-emerald-400/20 text-xs text-emerald-200 leading-6 flex gap-2"><CheckCircle2 className="w-5 h-5 shrink-0"/>{message}</div>:isAuthenticated?<form onSubmit={submit} className="mt-6 space-y-3"><textarea value={summary} onChange={e=>setSummary(e.target.value)} maxLength={1600} rows={3} placeholder="نبذة مختصرة عن خبرتك — اختياري" className="w-full glass-input rounded-xl px-4 py-3 text-sm outline-none resize-none"/><label className="block text-xs text-slate-400">سنوات الخبرة<input value={years} onChange={e=>setYears(e.target.value)} inputMode="numeric" className="mt-1.5 w-full glass-input rounded-xl px-4 py-3 text-sm outline-none"/></label><label className="flex items-start gap-2 p-3 rounded-xl bg-white/5 border border-white/10 text-xs text-slate-300 leading-6"><input type="checkbox" checked={declare} onChange={e=>setDeclare(e.target.checked)} className="mt-1"/><span>أقر أنني كويتي وأفهم أن هذا إقرار مني وليس تحققًا حكوميًا من المنصة.</span></label>{error&&<div className="text-xs text-rose-300">{error}</div>}<button disabled={!declare||busy} className="w-full py-3 rounded-xl bg-emerald-400 text-slate-950 font-black text-sm disabled:opacity-40 flex items-center justify-center gap-2"><UserCheck className="w-4 h-4"/>{busy?'جارٍ الإرسال…':'تقديم الطلب'}</button></form>:<div className="mt-6 p-4 rounded-2xl bg-amber-500/5 border border-amber-400/15 text-xs text-slate-300">سجّل الدخول من أعلى الصفحة ثم ارجع لهذه الفرصة لإرسال طلب التوظيف.</div>}</div></div>}
  </section>;
};
